/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoordinatorsRouteImport } from './routes/coordinators'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DepartmentsIndexRouteImport } from './routes/departments.index'
import { Route as DepartmentsSlugRouteImport } from './routes/departments.$slug'
import { Route as FormsFormIdRouteImport } from './routes/forms.$formId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinatorsRoute = CoordinatorsRouteImport.update({
  id: '/coordinators',
  path: '/coordinators',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsIndexRoute = DepartmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DepartmentsRoute,
} as any)
const DepartmentsSlugRoute = DepartmentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DepartmentsRoute,
} as any)
const FormsFormIdRoute = FormsFormIdRouteImport.update({
  id: '/forms/$formId',
  path: '/forms/$formId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coordinators': typeof CoordinatorsRoute
  '/departments': typeof DepartmentsRouteWithChildren
  '/doctors': typeof DoctorsRoute
  '/login': typeof LoginRoute
  '/departments/$slug': typeof DepartmentsSlugRoute
  '/forms/$formId': typeof FormsFormIdRoute
  '/departments/': typeof DepartmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coordinators': typeof CoordinatorsRoute
  '/doctors': typeof DoctorsRoute
  '/login': typeof LoginRoute
  '/departments/$slug': typeof DepartmentsSlugRoute
  '/forms/$formId': typeof FormsFormIdRoute
  '/departments': typeof DepartmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coordinators': typeof CoordinatorsRoute
  '/departments': typeof DepartmentsRouteWithChildren
  '/doctors': typeof DoctorsRoute
  '/login': typeof LoginRoute
  '/departments/$slug': typeof DepartmentsSlugRoute
  '/forms/$formId': typeof FormsFormIdRoute
  '/departments/': typeof DepartmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coordinators'
    | '/departments'
    | '/doctors'
    | '/login'
    | '/departments/$slug'
    | '/forms/$formId'
    | '/departments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coordinators'
    | '/doctors'
    | '/login'
    | '/departments/$slug'
    | '/forms/$formId'
    | '/departments'
  id:
    | '__root__'
    | '/'
    | '/coordinators'
    | '/departments'
    | '/doctors'
    | '/login'
    | '/departments/$slug'
    | '/forms/$formId'
    | '/departments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoordinatorsRoute: typeof CoordinatorsRoute
  DepartmentsRoute: typeof DepartmentsRouteWithChildren
  DoctorsRoute: typeof DoctorsRoute
  LoginRoute: typeof LoginRoute
  FormsFormIdRoute: typeof FormsFormIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinators': {
      id: '/coordinators'
      path: '/coordinators'
      fullPath: '/coordinators'
      preLoaderRoute: typeof CoordinatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/': {
      id: '/departments/'
      path: '/'
      fullPath: '/departments/'
      preLoaderRoute: typeof DepartmentsIndexRouteImport
      parentRoute: typeof DepartmentsRoute
    }
    '/departments/$slug': {
      id: '/departments/$slug'
      path: '/$slug'
      fullPath: '/departments/$slug'
      preLoaderRoute: typeof DepartmentsSlugRouteImport
      parentRoute: typeof DepartmentsRoute
    }
    '/forms/$formId': {
      id: '/forms/$formId'
      path: '/forms/$formId'
      fullPath: '/forms/$formId'
      preLoaderRoute: typeof FormsFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DepartmentsRouteChildren {
  DepartmentsSlugRoute: typeof DepartmentsSlugRoute
  DepartmentsIndexRoute: typeof DepartmentsIndexRoute
}

const DepartmentsRouteChildren: DepartmentsRouteChildren = {
  DepartmentsSlugRoute: DepartmentsSlugRoute,
  DepartmentsIndexRoute: DepartmentsIndexRoute,
}

const DepartmentsRouteWithChildren = DepartmentsRoute._addFileChildren(
  DepartmentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoordinatorsRoute: CoordinatorsRoute,
  DepartmentsRoute: DepartmentsRouteWithChildren,
  DoctorsRoute: DoctorsRoute,
  LoginRoute: LoginRoute,
  FormsFormIdRoute: FormsFormIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
